MRapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MovieRecommender.urls')),
    path('detaile_app/', include('detaile_app.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

MovieRecommender/urls.py
from django.contrib import admin
from django.urls import path
from MovieRecommender import views
from django.conf import settings
from django.conf.urls.static import static
app_name='MovieRecommender'

urlpatterns = [


    path('signup/',views.signup,name="signup"),
    path('login/',views.user_login,name="login"),
    path('home/',views.home,name="home"),
    path('dashboard/',views.dashboard,name="dashboard"),
    path('addmovie/',views.addmovie,name="addmovie"),
    path('logout/',views.user_logout,name="logout"),
    path('profile/',views.profile,name="profile"),

]

detaile_app/urls.py
from django.urls import path

from detaile_app import views
from django.conf import settings
from django.conf.urls.static import static
app_name='detaile_app'

urlpatterns = [

      path("movieDetail/<int:movie_id>/",views.movieDetail,name="movieDetail"),
      path("SearchResult/",views.SearchResult,name="SearchResult"),
]

MovieRecommender/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Movie(models.Model):
    title=models.CharField(max_length=70)
    genres=models.CharField(max_length=70)
    year=models.CharField(max_length=70)
    image=models.ImageField(upload_to="movie_image")
    movieduration=models.CharField(max_length=70)
    description = models.TextField(blank=True)
    release_date = models.DateField(max_length=250,null=True)
    actors = models.CharField(max_length=750,null=True)
    trailer_link = models.URLField(max_length=250, unique=True,null=True)


def __str__(self):
        return str(self.pk)

class Rating(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,default=None)
    movie=models.ForeignKey(Movie,on_delete=models.CASCADE,default=None)
    rating=models.CharField(max_length=70)
    rated_date=models.DateTimeField(auto_now_add=True)



templates/Register.html
{% extends 'base.html' %}
{% block title %}Signup{% endblock title %}
{% block css %}

.wrapper{
        margin-bottom:200px;
}

{% endblock css %}
{% block content %}
<br>
<br>

<div class="container p-5 mb-5 wrapper">
     {% if messages %}
                {%for msg in messages%}
                {% if msg %}   <div class="alert alert-{{msg.tags}} alert-dismissible fade show font-weight-bold text-primary w-50 ml-3 mt-5">{{msg}} <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button></div>{% endif %}
        {%endfor%}
        {% endif %}

<form action="" method="post" novalidate>
{% csrf_token %}
{% for fm in form %}
<span class="text-light">{{fm.label_tag}}</span>
<div class="form-group">
{{fm}}
</div>
{% if fm.errors %}
<div class="alert alert-danger lert-dismissible fade show">
{{fm.errors|striptags}}
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>

</div>
{% endif %}
{% endfor %}<br/>
  <input type="submit" value="submit" class="btn btn-primary">
</form>
</div>
{% endblock content %}

templates/addmovie.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Add Movie{% endblock title %}


{%block content%}
 {%if perms.MovieRecommender.add_movie%}
<div class="container  mt-2 p-5 mb-2">
<h1 class="text-center text-light">Add Movie</h1>  
  <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for fm in form  %}
        <span class="text-light font-weight-bold">{{fm.label_tag}}</span>
        <p>{{fm}}</p>
        {% endfor %}
        <input type="submit" class="btn btn-primary" value="Add">
        </form><br>
        {% if messages %}
        {%for msg in messages%}
        {% if msg %}   <div class="alert alert-success">{{msg}}</div>{% endif %}
        {%endfor%}
        {% endif %}
</form>
</div>
{% else %}
<h1 class="text-light mt-2 ml-2">Only Admin has Permission To Add Movie</h1>
{% endif %}
{%endblock content%} 

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Bootstrap CSS -->

<!--    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">-->
<!--    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">-->
   <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@100&family=Bitter:wght@200&family=Roboto:wght@300&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/5eafd2f154.js" crossorigin="anonymous"></script>

    <title>{% block title %}  {% endblock title %}</title>
    <style>{% block css %} {% endblock css %}</style>
  </head>
  <body>
    {% include 'navbar.html' %}
                        {% block content %}



                        {% endblock content %}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<!--    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>-->
<!--    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>-->
  </body>
</html>

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Dashboard{% endblock title %}
{% block css %}
         body{
                background: -webkit-linear-gradient(left, #556b2f, #808000);
            }
          .col-md-3
          {
          display: inline-block;
          margin-left:-4px;
          }

          .carousel-indicators .active {
          background-color: blue;
            }

          .col-md-3 img{

          width: 170px;
          height: 200px;
          }

          body .carousel-indicator li{
          background-color: blue;
          }

          body .carousel-indicators{
          bottom: 0;
          }

          body .carousel-control-prev-icon,
          body .carousel-control-next-icon{
          background-color: blue;
          }

          .carousel-control-prev,
          .carousel-control-next{
          top: auto;
          bottom: auto;
          padding-top: 222px;
          }
        body .no-padding{
           padding-left: 0,
           padding-right: 0;
           }

        .wrapper{

        margin-bottom:200px;
        }


 {% endblock %}

{% block content %}
<div class="container wrapper">
     {% if messages %}
                {%for msg in messages%}
                {% if msg %}   <div class="alert alert-{{msg.tags}} alert-dismissible fade show font-weight-bold text-primary w-50 ml-3 mt-5">{{msg}} <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button></div>{% endif %}
                {%endfor%}
                {% endif %}

    <!--Slideshow starts here -->
    {% for movie, range, nSlides in allMovies %}
    <h5 class="my-4 text-light"><u>{{movie.0.genres}}</u></h5>
<div class="row">
    <div id="demo{{forloop.counter}}" class="col carousel slide my-3" data-ride="carousel">
    <ul class="carousel-indicators">
      <li data-target="#demo{{forloop.counter}}" data-slide-to="0" class="active"></li>

       {% for i in range %}
      <li data-target="#demo{{forloop.parentloop.counter}}" data-slide-to="{{i}}" ></li>
      {% endfor %}
    </ul>


    <div class="container carousel-inner no-padding">

      <div class="carousel-item active">
        <div class="col-xs-3 col-sm-3 col-md-3">


          <div class="card" style="width: 18rem">
             <img class="card-img-top" src="{{movie.0.image.url}}"  alt="Card image cap" style="height:250px; width:85%; objet-fit:cover;">
                      <div class="card-body">
                        <h5 class="card-title">{{movie.0.title}}</h5>
                         <form action="" method="post" class="range-field">
                                                                        {% csrf_token %}  
                                                                        <input type="hidden" name="movieid" value="{{movie.0.id}}">
                                                                        <input type="hidden" name="userid" value="{{user.id}}">
                                                                        {{rform.as_p}}
                                                                        <div class="showrating">
                                                                        
                                                                        </div>
                                                                        <input type="submit" class="btn btn-primary" value="Submit">
                        </form>
                      </div>

                      <div class="card-footer" style="text-align:center;">
                          <small class="text-muted">
                              <h6><b><i>{{movie.0.genres}}</i></b> -<i>{{movie.0.movieduration}}</i></h6>
                          </small>
                     </div>
          </div>
       </div>


        {% for i in movie|slice:"1:"%}
        <div class="col-xs-3 col-sm-3 col-md-3">
         <div class="card" style="width: 18rem">
             <img class="card-img-top" src="{{i.image.url}}"  alt="Card image cap" style="height:250px; width:85%; objet-fit:cover;">
                      <div class="card-body">
                        <h5 class="card-title">{{i.title}}</h5>
                         <form action="" method="post" class="range-field">
                                                                        {% csrf_token %}  
                                                                        <input type="hidden" name="movieid" value="{{i.id}}"/>
                                                                        <input type="hidden" name="userid" value="{{user.id}}"/> 
                                                                        {{rform.as_p}}
                                                                        <div class="showrating">
                                                                        
                                                                        </div>
                                                                        <input type="submit" class="btn btn-primary" value="Submit">
                        </form>
                      </div>       
                      <div class="card-footer" style="text-align:center;">
                          <small class="text-muted"><h6><b><i>{{i.genres}}</i></b> -<i>{{i.movieduration}}</i></h6>
                        </small>
                     </div>
          </div>
        </div>
        {% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last %}
      </div><div class="carousel-item">
        {% endif %}

        {% endfor %}
    </div>



</div>
</div>
    <!-- left and right controls for the slide -->
    <a class="carousel-control-prev" href="#demo{{forloop.counter}}" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#demo{{forloop.counter}}" data-slide="next">
        <span class="carousel-control-next-icon"></span>
    </a>
        </div>
    {% endfor %}
</div>
 {% endblock %}




 

templates/detailes.html
{% extends 'base.html' %}
{% block css %}
     body{
         background-color:light green;
        }
    .my_detail_image{
           width: 50%;
          height: 45%;

          }
    img{
        width: 100%;
        height: 100%;
        objet-fit:cover;
      }
    .my_movie_title{
        font-size:30px;
        text_transform:uppercase;
        letter-spacing:.2em;
        padding-top:15px;
        padding-bottom-10px;
     }
    .my_movie_text{
        padding-right:20px
        font-size:20px;
    }
{% endblock %}

{% block content %}
<br>

<div class="container-fluide" style="background-color:#9BAF0B;">
<br>
<div class="row">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
<div class="my_image py-5 pl-5 pt-5" style="width:75%;height:65%;">
                <img src="{{ detail.image.url }}" alt="{{detail.title}}" style="width:100%;height:85%;align:center;">
                    </div>
            </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 py-3 pr-4 pt-3 pb-3">
            <div class="text-dark">
                            <h1 class="my_movie_title"><b>{{detail.title}}</b></h1>
                <p class="my_title"><b>Movie Description:</b></p>
            <p class="text-justify my_movie_text">{{detail.description}}</p>
 <p class="my_title"><b>Movie release date:</b></p>
            <p class="text-justify my_movie_text">{{detail.release_date}}</p>
                 <p class="my_title"><b>Movie actors:</b></p>
            <p class="text-justify my_movie_text">{{detail.actors}}</p>
                <p class="my_title"><b>Movie geners:</b></p>
            <p class="text-justify my_movie_text">{{detail.genres}}</p>
                <p class="my_title"><b>Movie trailer link:</b></p>
            <p class="text-justify my_movie_text">{{detail.trailer_link}}</p>

            </div>
                </div>

<!--            </div>-->
    </div>
</div>

{% endblock %}



templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block css %}
            body{
                background: -webkit-linear-gradient(left, #556b2f, #808000);
            }
          .col-md-3
          {
          display: inline-block;
          margin-left:-4px;
          }

          .carousel-indicators .active {
          background-color: blue;
            }

          .col-md-3 img{

          width: 170px;
          height: 200px;
          }

          body .carousel-indicator li{
          background-color: blue;
          }

          body .carousel-indicators{
          bottom: 0;
          }

          body .carousel-control-prev-icon,
          body .carousel-control-next-icon{
          background-color: blue;
          }

          .carousel-control-prev,
          .carousel-control-next{
          top: auto;
          bottom: auto;
          padding-top: 222px;
          }
        body .no-padding{
           padding-left: 0,
           padding-right: 0;
           }

        .wrapper{

        margin-bottom:200px;
        }


 {% endblock %}

{% block content %}
<br>
<br>

<div class="container wrapper">
{% if  recommended%}
<h5 class="my-4 text-light">Recommended Movie For You</h5>
<div class="row">
{% for item in recommended %}
<div class="col-4 mb-2">
        <div class="card" style="width: 18rem">
                <img class="card-img-top" src="{{item.image}}"  alt="Card image cap" style="height:250px; width:100%; objet-fit:cover;">
                <div class="card-footer" style="text-align:center;">
                    <small class="text-muted">
                        <h6><b><i>{{item.genres}}</i></b> -<i>{{item.movieduration}}</i></h6>

                    </small>

                </div>
        </div>
</div>
{% endfor %}
</div>
{% else %}
<h5 class="my-4 text-light">No Recommended Movie Found</h5>
{% endif %}

<br><br>
    <!--Slideshow starts here -->
    {% for movie, range, nSlides in allMovies %}

    <h5 class="my-4 text-light">Filtered By:{{movie.0.genres}}</h5>
<div class="row">
    <div id="demo{{forloop.counter}}" class="col carousel slide my-3" data-ride="carousel">
    <ul class="carousel-indicators">
      <li data-target="#demo{{forloop.counter}}" data-slide-to="0" class="active"></li>

       {% for i in range %}
      <li data-target="#demo{{forloop.parentloop.counter}}" data-slide-to="{{i}}" ></li>
      {% endfor %}
    </ul>


    <div class="container carousel-inner no-padding">

      <div class="carousel-item active">
        <div class="col-xs-3 col-sm-3 col-md-3">

            <div class="card" style="width: 18rem">
             <img class="card-img-top" src="{{movie.0.image.url}}" style="height:250px; width:85%; objet-fit:cover;" alt="Card image cap" >
                      <div class="card-body">
                        <h5 class="card-title">{{movie.0.title}}</h5>
                      </div>
                      <div class="card-footer" style="text-align:center;">
                          <small class="text-muted"><h6><b><i>{{movie.0.genres}}</i></b> -<i>{{movie.0.movieduration}}</i></h6></small>

                            <a href="{% url 'detaile_app:movieDetail' movie.0.id %}" class="btn btn-primary">Read More</a>
                          </small>
                     </div>
          </div>
       </div>
       {% for i in movie|slice:"1:"%}
        <div class="col-xs-3 col-sm-3 col-md-3">
         <div class="card" style="width: 18rem">
             <img class="card-img-top" src="{{i.image.url}}"  alt="Card image cap" style="height:250px; width:85%; objet-fit:cover;">
                      <div class="card-body">
                        <h5 class="card-title">{{i.title}}</h5>
                      </div>
                      <div class="card-footer" style="text-align:center;">
                        <small class="text-muted">
                            <h6><b><i>{{i.genres}}</i></b>-<i>{{i.movieduration}}</i></h6>

                            <a href="{% url 'detaile_app:movieDetail' i.id %}" class="btn btn-primary">Read More</a>
 </small>
                     </div>
          </div>
        </div>
        {% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last %}
      </div><div class="carousel-item">
        {% endif %}

        {% endfor %}
    </div>
</div>
</div>
    <!-- left and right controls for the slide -->
    <a class="carousel-control-prev" href="#demo{{forloop.counter}}" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#demo{{forloop.counter}}" data-slide="next">
        <span class="carousel-control-next-icon"></span>
    </a>
        </div>
    {% endfor %}
</div>
 {% endblock %}





templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock title %}

{% block content %}
<div class="container p-5 mb-5">
<form action="" method="post" novalidate>
{% csrf_token %}
{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger">{{error}}</div>
{% endfor %}
{% endif %} <br>
{% for fm in  form %}
<span class="text-light">{{fm.label_tag}}</span>
<p>
{{fm}}
</p>
{% if fm.errors  %}
<div class="alert alert-danger">
{{fm.errors|striptags}}
</div>
{% endif %}
{% endfor %} <br>
<input type="submit" value="Login" class="btn btn-warning"><br>
</form>
</div>
{% endblock content %}

templates/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'MovieRecommender:home' %}">Movie Recommender</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'MovieRecommender:home' %}">Home</a>
      </li>
      {% if  request.user.is_authenticated %}
       <li class="nav-item">
        <a class="nav-link" href="{% url 'MovieRecommender:dashboard' %}">Dashboard</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="{% url 'MovieRecommender:addmovie' %}">Add Movie</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="{% url 'MovieRecommender:profile' %}">Profile</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="{% url 'MovieRecommender:logout' %}">Logout</a>
      </li>
      {% endif %}
      {%if not request.user.is_authenticated%}
       <li class="nav-item">
        <a class="nav-link" href="{% url 'MovieRecommender:signup' %}">Register</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="{%url 'MovieRecommender:login'%}">Login</a>
      </li>
      {%endif%}

    </ul>
      <form class="form-inline ml-auto" action="{% url 'detaile_app:SearchResult' %}" method="get">
        {% csrf_token %}
          <input class="form-inline-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-success my-2 my-sm-0" type="submit"><i class="fa-solid fa-magnifying-glass"></i>Search</button>
      </form>
  </div>
</nav>

<nav class="navbar fixed-bottom navbar-expand-lg navbar-dark bg-dark">---------

</nav>

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
.body {background-color:#9BAF0B;
        }
{% endblock%}


{% block content %}

<div class="body pb-5">
    <br>
<div>
  <p class="text-center my_search_text  pt-5">You have search for :<b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx_auto">

        {% for item in movies %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">

            <div class="card text-center" style="min-width:18rem;">
                <a href="{{item.get_url}}"><img class="card-img-top my_image" src="{{item.image.url}}" alt="{{item.title}}"></a>
                <div class="card-body">
                    <h4>{{item.title}}</h4>
                    <h6 class="text-muted"><p><b><i>{{item.genres}}</i> </b>-<i>{{item.movieduration}}</i></p></h6>

                </div>
                <a href="{% url 'detaile_app:movieDetail' item.id %}" class="btn btn-primary">Read More</a>
            </div>

        </div>
      {% empty %}
            <div class="row mx_auto">
                <p class="text-center my_search_text"> 0 result found</p>
            </div>
        {% endfor %}
    </div>
</div>
<br>


</div>

{% endblock %}